#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

if [ -f .emoji ]
then
    branch=$(git symbolic-ref --short HEAD)
    emoji=$(cat .emoji)
    message=$(cat "$1")
    if echo "$message" | (! grep -q "^${branch} ${emoji}*")
    then
        echo "$branch $emoji $(cat $1)" > "$1"
    fi
fi

